# config/__init__.py

"""Makes configuration variables easily accessible."""

from .behaviour import (
    VIEWS,
    DEFAULT_VIEW,
    CALC_METHODS,
    DEFAULT_CALC_METHOD_TEAM,
    DEFAULT_CALC_METHOD_ATHLETE,
    ROUNDING_STEP,
    EVENTS_ORDER,
    LEVEL_OPTIONS_PREFIX,
    DEFAULT_SHOW_CURRENT_YEAR_ONLY,
    DEFAULT_FIT_Y_AXIS_ATHLETE,
    MEET_VIEW_LEVEL_ORDER,
    MEET_VIEW_EVENTS_TO_GRAPH,
    MEET_VIEW_TEAM_SCORE_Y_RANGE
)

from .plot import (
    YAxisRange,
    DEFAULT_Y_RANGE,
    COMPARISON_BAR_Y_RANGE,
    COMMON_LAYOUT_ARGS,
    COMMON_LINE_TRACE_ARGS,
    COMMON_BAR_TRACE_ARGS,
    XAXIS_TICKFONT_SIZE,
    YAXIS_TICKFONT_SIZE,
    MARKER_TEXTFONT_SIZE,
    STAR_ANNOTATION_FONT_SIZE
)

from .ui import (
    EVENT_COLORS,
    LEVEL_ORDER,
    LEVEL_COLORS,
    DARK_CARD_CSS,
    FONT_FAMILY,
    TAB_FONT_SIZE,
    CUSTOM_TAB_CSS
)

__all__ = [
    # behaviour
    "VIEWS",
    "DEFAULT_VIEW",
    "CALC_METHODS",
    "DEFAULT_CALC_METHOD_TEAM",
    "DEFAULT_CALC_METHOD_ATHLETE",
    "ROUNDING_STEP",
    "EVENTS_ORDER",
    "LEVEL_OPTIONS_PREFIX",
    "DEFAULT_SHOW_CURRENT_YEAR_ONLY",
    "DEFAULT_FIT_Y_AXIS_ATHLETE",
    "MEET_VIEW_LEVEL_ORDER",
    "MEET_VIEW_EVENTS_TO_GRAPH",
    "MEET_VIEW_TEAM_SCORE_Y_RANGE",
    # plot
    "YAxisRange",
    "DEFAULT_Y_RANGE",
    "COMPARISON_BAR_Y_RANGE",
    "COMMON_LAYOUT_ARGS",
    "COMMON_LINE_TRACE_ARGS",
    "COMMON_BAR_TRACE_ARGS",
    "XAXIS_TICKFONT_SIZE",
    "YAXIS_TICKFONT_SIZE",
    "MARKER_TEXTFONT_SIZE",
    "STAR_ANNOTATION_FONT_SIZE",
    # ui
    "EVENT_COLORS",
    "LEVEL_ORDER",
    "LEVEL_COLORS",
    "DARK_CARD_CSS",
    "FONT_FAMILY",
    "TAB_FONT_SIZE",
    "CUSTOM_TAB_CSS"
] 