[theme]
primaryColor="#6200EE"  # Example Material Purple
backgroundColor="#FFFFFF" # White background
secondaryBackgroundColor="#F0F2F6" # Light gray for sidebar/expanders
textColor="#262730" # Dark text
font="sans serif" # Or "Roboto", "Lato", etc. (ensure font is available)